config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  devise_for :users
  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create show]
    resources :reviews, only: %i[create show]
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: %i[destroy show]
  resources :users, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'is already in the list' }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :rating, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, :name, presence: true
  has_many :movies, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def set_locale
    I18n.load_path += Dir[File.expand_path('config/locales') + '/*.yml']
    I18n.locale = :fr
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:list]
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = current_user.lists.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    # @list = current_user.lists.find_by(id: params[:id]) || current_user.lists.first
    @list = current_user.lists.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @movies = Movie.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def set_review
    @review = current_user.reviews.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show]

  def show
    @lists = current_user.lists.all
    @list = current_user.reviews.all
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajoutez un film à votre <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for [list, bookmark] do |f| %>
        <div class="modal-body">
          <%= f.association :movie, required: false, collection: Movie.all.order(:title), prompt: "Sélectionnez un film", input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :comment, placeholder: "Entrez un commentaire sur le film" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Ajouter un film", class: "btn btn-flat" %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ajoutez un film à votre <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for [list, bookmark] do |f| %>
        <div class="modal-body">
          <%= f.association :movie, required: false, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :comment, placeholder: "Entrez un commentaire sur le film" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Ajouter un film", class: "btn btn-flat" %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1>Enregistrez tout type de films</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">Mes listes</h3>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-flat" %>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="co-12 col-sm-6 col-md-4 mb-3">
        <%= link_to list_path(list), class:"text-decoration-none" do %>
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path(@image.sample) %>)">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Créer une nouvelle liste</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, required: false, placeholder: 'Drama' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @list.photo.key, crop: :fill %>)">
    <h1><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>
<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        add a movie
      </button>
      <%= link_to "delete this list", list_path(@list), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    </div>
  </div>
  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <hr class="my-5">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @list.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>
      <% @list.reviews.each do |review| %>
        <div>
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
        <h5>Add your review</h5>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { data: { controller: "star-rating" } } %>
          <%= f.submit class:"btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "bookmarks/modal", list: @list, bookmark: @bookmark %>

app/views/movies/index.html.erb
<div class="container">
  <h1 class="text-center">Movies</h1>
  <p class="text-center">Collectez, organisez et partagez. Les listes sont le moyen idéal pour regrouper les films.</p>
<hr>

  <div class="container text-center" data-controller="insert-movies">
    <form class="row g-2 justify-content-center py-5" id="search-form"
      data-action="submit->insert-movies#search">
      <div class="col-4">
        <input type="text" class="form-control" placeholder="Find movie" id="search-input"
          data-insert-movies-target="input">
      </div>
      <div class="col-1">
        <input type="submit" class="btn btn-primary">
      </div>
    </form>
    <ul id="results" class="list-group list-group-horizontal"
      data-insert-movies-target="results"
      data-controller="init-sortable">
    </ul>
    <hr>
    <div class="row">
      <div class="col pt-1" data-controller="disable-button">
        <button class="btn btn-primary btn-lg"
          data-action="click->disable-button#disable"
          data-disable-button-target="button">
          Click me!
        </button>
        <a href="#" class="d-none ms-2"
          data-disable-button-target="link"
          data-action="click->disable-button#reset">
          Reset
        </a>
      </div>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="row">
  <div class="col-12 col-sm-6">
    <h3>Commentaires</h3>
    <% if @list.reviews.empty? %>
      <small><em class="text-muted">Soyez le premier à consulter cette liste</em></small>
    <% end %>
    <% @list.reviews.each do |review| %>
      <div>
        <% review.rating.times do %>
          <i class="fas fa-star star-yellow"></i>
        <% end %>
        <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> il y a</em></small>
        <p class="mb-0"><%= review.comment %></p>
      </div>
      <hr>
    <% end %>
  </div>
  <div class="col-12 col-sm-6">
    <div class="bg-white rounded p-3">
      <h5>Ajoutez votre avis</h5>
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :comment, placeholder: "Ajoutez votre avis ici..." %>
        <%= f.input :rating, as: :select, collection: (1..5), required: false, prompt: "Quelle est votre note", input_html: { data: { controller: "star-rating" } } %>
        <%= f.submit class:"btn btn-flat" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon p-2">
  <%= link_to root_path do %>
    <%= image_tag "logo.png", alt: "movies", class: "avatar-square" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
          <%= image_tag "profile.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <li class="nav-item dropdown">
          <%= link_to "PROFILE", new_user_session_path, class: "nav-link", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="navbarDropdown">
            <%= current_user.name %>
            <%= link_to "Home", root_path, class: "dropdown-item" %>
            <%# <%= link_to "Profile", user_path(@user), class: "dropdown-item" %>
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>

            <%= link_to "Listes", lists_path, class: "dropdown-item" %>
            <%= link_to "Commentaires", lists_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
       <% else %>
        <li class="nav-item">
          <%= link_to "CONNEXION", new_user_session_path, class:'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item active">
        <%= link_to "FILMS", movies_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "LISTES", lists_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "MEMBRES", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "REVUES", root_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container p-4">
  <div class="row justify-content-between">
    <div class="profile-avatar">
      <%= image_tag 'profile.png', class:'avatar-large' %>
    </div>
    <div class="d-flex align-items-center">
      <h1 style="font-size: 29px"><%= @user.name %></h1>
    </div>
    <div class="col-sm-4" data-controller="weather">
      <form class="d-flex my-5" data-action="submit->weather#fetchWeather">
        <input type="text" placeholder="Enter city" class="form-control flex-grow-1" data-weather-target="input">
        <a href="" class="position d-flex align-items-center" data-action="click->weather#fetchWeatherByCoordinates"><i class="bi bi-geo-alt"></i></a>
        <input type="submit" value="Get the weather" class="btn btn-primary ms-3">
      </form>
      <div class="card mt-4 mb-5">
        <div class="card-body">
          <h3>Weather in <span data-weather-target="city"> <!-- TODO: CITY NAME --> </span></h3>
          <h3 class="text-secondary" data-weather-target="date"><!-- TODO: DATE --></h3>
          <div>
            <p data-weather-target="description"><!-- TODO: DESCRIPTION --></p>
            <div class="d-flex">
              <img src="" alt="Weather Icon" data-weather-target="icon">
              <h2 data-weather-target="temperature"><!-- TODO: TEMPERATURE --></h2>
            </div>
          </div>
        </div>
      </div>
    </div>
      <script src="main.js"></script>
  </div>
  <br>
  <nav>
    <div class="nav nav-tabs justify-content-center border border-secondary" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</button>
      <button class="nav-link" id="nav-activite-tab" data-bs-toggle="tab" data-bs-target="#nav-activite" type="button" role="tab" aria-controls="nav-activite" aria-selected="true">Activité</button>
      <button class="nav-link" id="nav-films-tab" data-bs-toggle="tab" data-bs-target="#nav-films" type="button" role="tab" aria-controls="nav-films" aria-selected="true">Films</button>
      <button class="nav-link" id="nav-listes-tab" data-bs-toggle="tab" data-bs-target="#nav-listes" type="button" role="tab" aria-controls="nav-listes" aria-selected="true">Listes</button>
      <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</button>
      <button class="nav-link" id="nav-Commentaire-tab" data-bs-toggle="tab" data-bs-target="#nav-Commentaire" type="button" role="tab" aria-controls="nav-Commentaire" aria-selected="false">Commentaires</button>
    </div>
  </nav>
  <br>
  <div class="tab-content " id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
      <p><%= @user.email %></p>

    </div>
    <div class="tab-pane fade" id="nav-activite" role="tabpanel" aria-labelledby="nav-activite-tab" tabindex="0">
    ....
    </div>
    <div class="tab-pane fade" id="nav-films" role="tabpanel" aria-labelledby="nav-films-tab" tabindex="0">
      <section id="favourites" class="section body-text -hero shown-for-owner" data-owner="markyuna">
        <h2 class="section-heading">Films préférés</h2>
        <hr>
        <p class="body-text">Don’t forget to select your <a href="/settings/">films préférés</a>!</p>
      </section>
    </div>
    <div class="tab-pane fade" id="nav-listes" role="tabpanel" aria-labelledby="nav-listes-tab" tabindex="0">
      <div class="d-flex align-items-center justify-content-between mb-3">
        <h3 class="mb-0">Mes listes</h3>
        <%= link_to "Create a movie list", new_list_path, class: "btn btn-flat" %>
      </div>
      <div class="row">
        <% @lists.each do |list| %>
          <div class="co-12 col-sm-6 col-md-4 mb-3">
            <%= link_to list_path(list), class:"text-decoration-none" do %>
              <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path(@image.sample) %>)">
                <%= list.name %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab" tabindex="0">
      <div class="row justify-content-center">
        <div class="col-12 col-md-6 col-lg-4">
          <form action="#" class="row">
            <h2 class="text-center mb-5">Contact nous</h2>
            <div class="col-6 mb-3">
              <label for="first-name" class="form-label">Votre prenom</label>
              <input type="text" class="form-control" id="first-name" placeholder="Bob">
            </div>
            <div class="col-6 mb-3">
              <label for="subject" class="form-label">Sujet :</label>
              <input type="text" class="form-control" id="subject" name="subject" required>
            </div>
            <div class="col-12 mb-3">
              <label for="email" class="form-label">Your email</label>
              <input type="email" class="form-control" id="email" placeholder="bob@gmail.com">
            </div>
            <div class="col-12 mb-3">
              <label for="message" class="form-label">Message :</label>
              <textarea class="form-control" id="message" name="message" required></textarea>
            </div>
            <div class="col-12 mb-3">
              <label for="referrer" class="form-label">How do you know us?</label>
              <select id="referrer" class="form-select">
                <option value="">Facebook</option>
                <option value="">Google Search</option>
                <option value="">A friend</option>
              </select>
            </div>
            <div class="col-12">
              <input type="submit" value="Sign up" class="btn btn-primary btn-lg w-100">
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-Commentaire" role="tabpanel" aria-labelledby="nav-Commentaire-tab" tabindex="0">

    </div>
  </div>
</div>